- name: Initialize BorgBase Repository
  hosts: "{{ host }}"
  vars_files:
    - group_vars/forge.yaml
    - group_vars/default.yaml
  tasks:
    - name: Check if Configuration File Exists
      stat:
        path: "{{ config_directory }}/{{ domain }}.yaml"
      register: config_file

    - name: Create Configuration File
      template:
        src: "templates/config.yaml.j2"
        dest: "{{ config_directory }}/{{ domain }}.yaml"
        mode: "0600"
      when: not config_file.stat.exists

    - name: Initialize Repository
      expect:
        command: /home/forge/.local/bin/borgmatic init --encryption repokey -c {{ config_directory }}/{{ domain }}.yaml
        responses:
          (?i)(yes/no/[fingerprint]): 'y'
          (?i)fingerprint: 'yes'
      register: initialize_repo

    - debug:
        msg: "{{ initialize_repo }}"

    - name: Create Initial Backup
      shell:
        cmd: /home/forge/.local/bin/borgmatic create -c {{ config_directory }}/{{ domain }}.yaml --stats
      register: create_backup

    - debug:
        msg: "{{ create_backup.stdout_lines }}"

    - name: List Backup
      shell:
        cmd: /home/forge/.local/bin/borgmatic list -c {{ config_directory }}/{{ domain }}.yaml --short --last 1
      register: list_backup

    - set_fact:
        archive_name: "{{ list_backup.stdout_lines[1] }}"

    - debug:
        msg: "{{ archive_name }}"

