---
- name: Restore a Site from Backup
  hosts: "{{ backupServer }}"
  vars_files:
    - "group_vars/forge.yaml"
    - "group_vars/site.yaml"
    - "group_vars/default.yaml"
  pre_tasks:
    - name: Generate Token
      include_tasks: "tasks/create_token.yaml"
      when: logTask == 'true'
  tasks:
    - name: Check if Backup Folder Exists
      stat:
        path: /root/backups/{{ domain }}/{{ location }}/
      register: backupFolder

    - name: Restore Files from the Backup Server
      synchronize: 
        src: "/root/backups/{{ domain }}/{{ location }}/" 
        dest: "{{ srcRootFolder }}/"
        mode: pull
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=*.log"
          - "--exclude=*_log"
      when: (backupFolder.stat.exists)
      ignore_errors: yes
      delegate_to: "{{ host }}"
