---
- name: Get Token
  uri:
    url: "{{ wc_api_endpoint }}/oauth/token"
    method: POST
    body_format: form-urlencoded
    body:
      client_id: 3
      client_secret: "{{ wc_client_secret }}"
      grant_type: password
      scope: "*"
      username: "{{ wc_api_username }}"
      password: "{{ wc_api_password }}"
  delegate_to: localhost
  register: token

- set_fact:
    accessToken: "Bearer {{ token.json.access_token }}"