---
- name: Create a Website
  block:
    - name: Create Website in Laravel Forge
      uri:
        url: "{{ forgeBaseUri }}/servers/{{ serverID }}/sites"
        method: POST
        headers:
            Authorization: "{{ forgeApiToken }}"
            Accept: "application/json"
            Content-Type: "application/json"
        body:
            domain: "{{ fullUrl }}"
            project_type: "php"
            directory: "/public"
            username: "{{ isolatedUser }}"
            isolated: true
        body_format: json
        return_content: yes
        force_basic_auth: yes
      register: forgeSite

    - name: Pause for 60 seconds to finish creating the site
      pause:
        seconds: 60
  when: siteExists == false

- name: Setup WordPress Site
  block:
    - name: Setup WordPress Site in Laravel Forge
      uri:
        url: "{{ forgeBaseUri }}/servers/{{ serverID }}/sites/{{ forgeSite.json.site.id }}/wordpress"
        method: POST
        headers:
            Authorization: "{{ forgeApiToken }}"
            Accept: "application/json"
            Content-Type: "application/json"
        body:
            database: "{{ databaseName }}"
            user: "{{ forgeDatabaseUser.json.user.id }}"
        body_format: json
        return_content: yes
        force_basic_auth: yes

    - name: Pause for 60 seconds to finish setting up the site
      pause:
        seconds: 60
  when: (env == 'production') and (siteExists == false)