---
- name: Create a Website
  block:
    - name: Create a Website in Laravel Forge
      uri:
        url: "{{ forgeBaseUri }}/servers/{{ serverID }}/sites"
        method: POST
        headers:
            Authorization: "{{ forgeApiToken }}"
            Accept: "application/json"
            Content-Type: "application/json"
        body:
            domain: "{{ fullUrl }}"
            project_type: "php"
            directory: "/public"
            username: "{{ isolatedUser }}"
            isolated: true
        body_format: json
        return_content: yes
        force_basic_auth: yes
      register: forgeSite

    - name: Pause for 30 seconds to finish creating the site
      pause:
        seconds: 30
  when: siteExists == false

- name: Setup the Site from Git Repository
  block:
    - name: Clone Site from Git Repository
      uri:
        url: "{{ forgeBaseUri }}/servers/{{ serverID }}/sites/{{ forgeSite.json.site.id }}/git"
        method: POST
        headers:
            Authorization: "{{ forgeApiToken }}"
            Accept: "application/json"
            Content-Type: "application/json"
        body:
            provider: "{{ gitProvider }}"
            repository: "{{ gitRepository }}"
            branch: "{{ gitBranch }}"
            composer: true
        body_format: json
        return_content: yes
        force_basic_auth: yes

    - name: Pause for 60 seconds to finish setting up the site
      pause:
        seconds: 60
  when: forgeSite is defined and (siteExists == false)

- name: Install and Compile NPM Packages
  block:
    - name: Install and Compile NPM Packages
      uri:
        url: "{{ forgeBaseUri }}/servers/{{ serverID }}/sites/{{ forgeSite.json.site.id }}/commands"
        method: POST
        headers:
            Authorization: "{{ forgeApiToken }}"
            Accept: "application/json"
            Content-Type: "application/json"
        body:
            command: "yarn install && yarn run dev"
        body_format: json
        return_content: yes
        force_basic_auth: yes
        status_code: [200, 204]
      ignore_errors: yes
    
    - name: Pause for 30 seconds to finish compiling
      pause:
        seconds: 30
  when: forgeSite is defined