---
- name: Install Requirements
  become: "yes"
  package:
    name: "{{ borg_packages }}"
    state: present

- name: Install required Python Packages
  pip:
    name: "{{ borg_python_packages }}"
  when: borg_python_packages is defined