---
- name: Optimize Database
  become: yes
  become_user: "{{ isolatedUser }}"
  shell:
    cmd: wp db optimize
    chdir: "{{ rootFolder }}"
  args:
    executable: /bin/bash

- name: Clear the cache
  become: yes
  become_user: "{{ isolatedUser }}"
  shell:
    cmd: wp cache flush
    chdir: "{{ rootFolder }}"
  args:
    executable: /bin/bash

- name: Set wp-config.php Permissions
  become: yes
  become_user: "{{ isolatedUser }}"
  file:
    path: "{{ rootFolder }}/wp-config.php"
    mode: '644'